Run Date: Tue Jan 18 16:50:41 CST 2022
no change     ~\Miniconda3\Scripts\conda.exe
no change     ~\Miniconda3\Scripts\conda-env.exe
no change     ~\Miniconda3\Scripts\conda-script.py
no change     ~\Miniconda3\Scripts\conda-env-script.py
no change     ~\Miniconda3\condabin\conda.bat
no change     ~\Miniconda3\Library\bin\conda.bat
no change     ~\Miniconda3\condabin\_conda_activate.bat
no change     ~\Miniconda3\condabin\rename_tmp.bat
no change     ~\Miniconda3\condabin\conda_auto_activate.bat
no change     ~\Miniconda3\condabin\conda_hook.bat
no change     ~\Miniconda3\Scripts\activate.bat
no change     ~\Miniconda3\condabin\activate.bat
no change     ~\Miniconda3\condabin\deactivate.bat
no change     ~\Miniconda3\Scripts\activate
no change     ~\Miniconda3\Scripts\deactivate
no change     ~\Miniconda3\etc\profile.d\conda.sh
no change     ~\Miniconda3\etc\fish\conf.d\conda.fish
no change     ~\Miniconda3\shell\condabin\Conda.psm1
no change     ~\Miniconda3\shell\condabin\conda-hook.ps1
no change     ~\Miniconda3\Lib\site-packages\xontrib\conda.xsh
no change     ~\Miniconda3\etc\profile.d\conda.csh
no change     ~\.bash_profile
No action taken.
Updating Environment
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done
Installing pip dependencies: ...working... done
Internalizing Environment
Set Up Complete
============================= test session starts =============================
collecting ... collected 2 items

..\scr\tests\test_example.py::TestExample::test_example PASSED           [ 50%]
..\scr\tests\test_example.py::TestExample::test_fail_example FAILED      [100%]

================================== FAILURES ===================================
________________________ TestExample.test_fail_example ________________________

self = <scr.tests.test_example.TestExample object at 0x00000250D5407EE0>

    def test_fail_example(self):
        # Perform Web Search
        self.home_page.web_search(search_query='cookies')
    
        # Verify expected result is listed
>       assert self.results_page.is_expected_result_url_listed(search_result='https://docs.pytest.org/') is True
E       AssertionError: assert False is True
E        +  where False = <bound method WebResults.is_expected_result_url_listed of <scr.page_objects.example_web_result_page.WebResults object at 0x00000250D53E4070>>(search_result='https://docs.pytest.org/')
E        +    where <bound method WebResults.is_expected_result_url_listed of <scr.page_objects.example_web_result_page.WebResults object at 0x00000250D53E4070>> = <scr.page_objects.example_web_result_page.WebResults object at 0x00000250D53E4070>.is_expected_result_url_listed
E        +      where <scr.page_objects.example_web_result_page.WebResults object at 0x00000250D53E4070> = <scr.tests.test_example.TestExample object at 0x00000250D5407EE0>.results_page

..\scr\tests\test_example.py:18: AssertionError
- generated xml file: ~\pytest_framework_template\build\reports\Test_Report_18-01-22-1650.xml -
- generated html file: file://~\pytest_framework_template\build\reports\Test_Report_18-01-22-1650.html -
=========================== short test summary info ===========================
FAILED ..\scr\tests\test_example.py::TestExample::test_fail_example - Asserti...
======================== 1 failed, 1 passed in 38.09s =========================
Tearing Down Environment
